### ISSUE TITLE
Mac compile error: MSG_NOSIGNAL

### ISSUE THREAD

**Issue by mischnic** [cnlohr/cnping#46]
Not sure whether cnping or cnping_mac is the correct target, but both don't compile on macOS (10.13):

```
$ make cnping
cc  -g -Os -I/opt/X11/include -Wall   -c -o httping.o httping.c
httping.c:96:36: error: use of undeclared identifier 'MSG_NOSIGNAL'
                int rs = send( httpsock, buf, n, MSG_NOSIGNAL );
                                                 ^
1 error generated.
make: *** [<builtin>: httping.o] Error 1
```

```
$ make cnping_mac
gcc -o cnping cnping.c CNFGFunctions.c CNFGCocoaCGDriver.m os_generic.c ping.c -x objective-c -framework Cocoa -framework QuartzCore -lm -lpthread
cnping.c:344:27: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                        sprintf( stbuf, "%lu", samps );
                                         ~~~   ^~~~~
                                         %llu
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
cnping.c:358:55: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                        pinghost, globmaxtime*1000.0, globinterval*1000.0, globallost, globalrx, globallost*100.0/(globalrx+globallost) );
                                                                           ^~~~~~~~~~
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^~~~~~~~~~~
cnping.c:358:67: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                        pinghost, globmaxtime*1000.0, globinterval*1000.0, globallost, globalrx, globallost*100.0/(globalrx+globallost) );
                                                                                       ^~~~~~~~
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^~~~~~~~~~~
cnping.c:478:3: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                globallost, globalrx, globallost*100.0f/(globalrx+globallost), loss );
                ^~~~~~~~~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
cnping.c:478:15: warning: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
                globallost, globalrx, globallost*100.0f/(globalrx+globallost), loss );
                            ^~~~~~~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
5 warnings generated.
os_generic.c:281:2: warning: 'sem_init' is deprecated [-Wdeprecated-declarations]
        sem_init( sem, 0, 0 );
        ^
/usr/include/sys/semaphore.h:55:42: note: 'sem_init' has been explicitly marked deprecated here
int sem_init(sem_t *, int, unsigned int) __deprecated;
                                         ^
/usr/include/sys/cdefs.h:176:37: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((deprecated))
                                       ^
os_generic.c:288:2: warning: 'sem_getvalue' is deprecated [-Wdeprecated-declarations]
        sem_getvalue( os, &valp );
        ^
/usr/include/sys/semaphore.h:54:56: note: 'sem_getvalue' has been explicitly marked deprecated here
int sem_getvalue(sem_t * __restrict, int * __restrict) __deprecated;
                                                       ^
/usr/include/sys/cdefs.h:176:37: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((deprecated))
                                       ^
os_generic.c:305:2: warning: 'sem_destroy' is deprecated [-Wdeprecated-declarations]
        sem_destroy( os );
        ^
/usr/include/sys/semaphore.h:53:26: note: 'sem_destroy' has been explicitly marked deprecated here
int sem_destroy(sem_t *) __deprecated;
                         ^
/usr/include/sys/cdefs.h:176:37: note: expanded from macro '__deprecated'
#define __deprecated    __attribute__((deprecated))
                                       ^
3 warnings generated.
ping.c:58:4: warning: declaration does not declare anything [-Wmissing-declarations]
                        uint16_t        __unused;
                        ^~~~~~~~
1 warning generated.
Undefined symbols for architecture x86_64:
  "_StartHTTPing", referenced from:
      _main in cnping-a4c237.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:24: cnping_mac] Error 1
```

The second error can be reduced to the first with:
```diff
diff --git a/Makefile b/Makefile
index 63f799e..b0c9fcc 100644
--- a/Makefile
+++ b/Makefile
@@ -20,7 +20,7 @@ cnping : cnping.o CNFGFunctions.o CNFGXDriver.o os_generic.o ping.o httping.o
 cnping-mousey : cnping-mousey.o CNFGFunctions.o CNFGXDriver.o os_generic.o ping.o
        gcc $(CFLAGS) -o $@ $^ -lX11 -lm -lpthread $(LDFLAGS)

-cnping_mac : cnping.c CNFGFunctions.c CNFGCocoaCGDriver.m os_generic.c ping.c
+cnping_mac : cnping.c CNFGFunctions.c CNFGCocoaCGDriver.m os_generic.c ping.c httping.c
        gcc -o cnping $^ -x objective-c -framework Cocoa -framework QuartzCore -lm -lpthread

 cnping-mousey_mac : cnping-mousey.c CNFGFunctions.c CNFGCocoaCGDriver.m os_generic.c ping.c
```

**Comment by mischnic** [comment]
Would the Windows "solution" work for macOS as well?
https://github.com/cnlohr/cnping/blob/67bf9b73eefe1de63bed8608e7cb79250bea5f3d/httping.c#L9-L13

**Comment by cnlohr** [comment]
Looks like the right answer is to use SO_NOSIGPIPE

https://github.com/lpeterse/haskell-socket/issues/8

**Comment by cnlohr** [comment]
But for yes, temporarily I guess we could do it that way...

**Comment by mischnic** [comment]
> Looks like the right answer is to use SO_NOSIGPIPE

Like this?
```diff
> diff --git a/httping.c b/httping.c
index 0cf6a6e..2d4287d 100644
--- a/httping.c
+++ b/httping.c
@@ -86,6 +86,10 @@ reconnect:
                goto fail;
        }

+#ifndef MSG_NOSIGNAL
+       setsockopt(httpsock, SOL_SOCKET, SO_NOSIGPIPE, 1, sizeof(1));
+#endif
+
        errbuffer[0] = 0;

        while( 1 )
@@ -93,7 +97,12 @@ reconnect:
                char buf[8192];

                int n = sprintf( buf, "HEAD %s HTTP/1.1\r\nConnection: keep-alive\r\n\r\n", eurl?eurl:"/favicon.ico" );
+#ifdef MSG_NOSIGNAL
                int rs = send( httpsock, buf, n, MSG_NOSIGNAL );
+#else
+               int rs = send( httpsock, buf, n, 0);
+#endif
+
                double starttime = *timeouttime = OGGetAbsoluteTime();
                int breakout = 0;
                if( rs != n ) breakout = 1;
```

There seems to be no difference to `#define MSG_NOSIGNAL 0`.

But cnping-mousey always looks like this (regardleyy of _mac or the X11 version):
![bildschirmfoto 2018-07-17 um 10 50 28](https://user-images.githubusercontent.com/4586894/42806665-3b52bfc6-89af-11e8-885e-be63e9719589.png)

**Comment by cnlohr** [comment]
Mousey needs to be removed.  Only use cnping or searchnet.

`SO_NOSIGPIPE` is only used to prevent program crash if it fails to send.

Are you running as root?

**Comment by mischnic** [comment]
> Are you running as root?

Yes, otherwise I get : `Error: Failed to set TTL option.  Are you root?  Or can do sock_raw sockets?`

> SO_NOSIGPIPE is only used to prevent program crash if it fails to send.

How can I test that?

**Comment by cnlohr** [comment]
Unplug your ethernet device after the application has started.

Is it still not working at all for you?  Even when running as root?

**Comment by mischnic** [comment]
> Unplug your ethernet device after the application has started.

(= disabled Wifi). Is this correct?

![bildschirmfoto 2018-07-17 um 22 49 44](https://user-images.githubusercontent.com/4586894/42844604-ccace15e-8a13-11e8-9f78-1510c0df851b.png)

> Is it still not working at all for you? Even when running as root?

cnping(_mac) works fine with the `SO_NOSIGPIPE` change. With this:

> There seems to be no difference to `#define MSG_NOSIGNAL 0`.

I meant that both fixes behave the same way (= work fine).

**Comment by cnlohr** [comment]
That looks great.  Maybe OSX just decided to remove the signal functionality altogether?

**Comment by cnlohr** [comment]
Can you do a pull-request?
