### ISSUE TITLE
can't compile on Mac OS 10.9.5 - unknown type name n_short and n_time 

### ISSUE THREAD

**Issue by PmE8HW0KRfqa** [cnlohr/cnping#1]
```
make
cc  -g -Os   -c -o cnping.o cnping.c
In file included from cnping.c:13:
/usr/include/netinet/ip_icmp.h:92:4: error: unknown type name 'n_short'; did you
      mean 'u_short'?
                        n_short icd_id;
                        ^
/usr/include/sys/types.h:85:25: note: 'u_short' declared here
typedef unsigned short          u_short;
                                ^
In file included from cnping.c:13:
/usr/include/netinet/ip_icmp.h:93:4: error: unknown type name 'n_short'; did you
      mean 'u_short'?
                        n_short icd_seq;
                        ^
/usr/include/sys/types.h:85:25: note: 'u_short' declared here
typedef unsigned short          u_short;
                                ^
In file included from cnping.c:13:
/usr/include/netinet/ip_icmp.h:99:4: error: unknown type name 'n_short'; did you
      mean 'u_short'?
                        n_short ipm_void;
                        ^
/usr/include/sys/types.h:85:25: note: 'u_short' declared here
typedef unsigned short          u_short;
                                ^
In file included from cnping.c:13:
/usr/include/netinet/ip_icmp.h:100:4: error: unknown type name 'n_short'; did
      you mean 'u_short'?
                        n_short ipm_nextmtu;
                        ^
/usr/include/sys/types.h:85:25: note: 'u_short' declared here
typedef unsigned short          u_short;
                                ^
In file included from cnping.c:13:
/usr/include/netinet/ip_icmp.h:121:4: error: unknown type name 'n_time'
                        n_time its_otime;
                        ^
/usr/include/netinet/ip_icmp.h:122:4: error: unknown type name 'n_time'
                        n_time its_rtime;
                        ^
/usr/include/netinet/ip_icmp.h:123:4: error: unknown type name 'n_time'
                        n_time its_ttime;
                        ^
/usr/include/netinet/ip_icmp.h:126:14: error: field has incomplete type
      'struct ip'
                        struct ip idi_ip;
                                  ^
/usr/include/netinet/ip_icmp.h:126:11: note: forward declaration of 'struct ip'
                        struct ip idi_ip;
                               ^
8 errors generated.
make: *** [cnping.o] Error 1

```

**Comment by cnlohr** [comment]
woah... I don't know for sure, my first inclination is to add a -D_GNU_SOURCE to the compile flags.

**Comment by mischnic** [comment]
It compiled after adding some includes and copying the icmphdr struct definition from the WIN32 part. 
But then running fails: _Error: Failed to set TTL option_ . That might has to do something with `#define SOL_IP IPPROTO_IP`?

Patch
[mac.patch.txt](https://github.com/cnlohr/cnping/files/232003/mac.patch.txt)

**Comment by hackrid** [comment]
had the same issue. you must run it as root

**Comment by hackrid** [comment]
... or what ever you call it on osx ;)

**Comment by Yann-R** [comment]
Most of the time, when `n_short` and `n_time` are missing definitions on Mac around `ip_icmp`, the reason is missing `#include <netinet/ip.h>`

Sometimes, you already have `#include <netinet/in.h>`, which is not sufficient and can be replaced by the above `ip.h`that transitively includes `in.h`.

**Comment by cnlohr** [comment]
So... do changes need to be made on my part?

**Comment by mischnic** [comment]
I updated the code and now I get these errors after closing the cnping window using the button:
```
XIO:  fatal IO error 60 (Operation timed out) on X server "/private/tmp/com.apple.launchd.9Bj5LvF6tU/org.macosforge.xquartz:0"
      after 28747 requests (28453 known processed) with 0 events remaining.
```
Obvisouly, cnping exits, should I ignore the message?
(I was going to create a pull request)

**Comment by mischnic** [comment]
Can be closed (pr #10 & #11)

**Comment by Dauie** [comment]
Also, if you do have this issue after including:  Make sure that you are including <netinet/ip.h> before you include any libraries that reference the type alias n_short. i.g. <netinet/ip_icmp.h>
